### ISSUE TITLE
DbUp Migration - Timeout not being respected

### ISSUE THREAD

**Issue by null-reference** [johanclasson/vso-agent-tasks#8]
I'm encountering timeouts during longer running scripts even though I have set the Timeout (Control Options -> Timeout) to 0 which indicates an infinite timeout.

Is this Timeout field expected to work?

![image](https://cloud.githubusercontent.com/assets/6753679/20006911/38ba765a-a270-11e6-9c37-6bce6b4f840a.png)

Here is an example error from the logs...

_##[error]System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at System.Data.SqlClient.TdsParserStateObject.ReadSniError(TdsParserStateObject stateObj, UInt32 error)
at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
at System.Data.SqlClient.TdsParserStateObject.TryReadByte(Byte& value)
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
at DbUp.Support.SqlServer.SqlScriptExecutor.<>c__DisplayClass15_0.<Execute>b__1(Func`1 dbCommandFactory) in C:\projects\dbup\src\DbUp\Support\SqlServer\SqlScriptExecutor.cs:line 125
at DbUp.Engine.Transactions.NoTransactionStrategy.Execute(Action`1 action) in C:\projects\dbup\src\DbUp\Engine\Transactions\NoTransactionStrategy.cs:line 14
at DbUp.Engine.Transactions.DatabaseConnectionManager.ExecuteCommandsWithManagedConnection(Action`1 action) in C:\projects\dbup\src\DbUp\Engine\Transactions\DatabaseConnectionManager.cs:line 100
at DbUp.Support.SqlServer.SqlScriptExecutor.Execute(SqlScript script, IDictionary`2 variables) in C:\projects\dbup\src\DbUp\Support\SqlServer\SqlScriptExecutor.cs:line 106_

**Comment by johanclasson** [comment]
I have published a new version of the DbUp Migration task which should remove the timeout issue. Hope it works for you @null-reference!

**Comment by null-reference** [comment]
Thank you very much @johanclasson! It's working! Our team is very appreciative.
